### ISSUE TITLE
Multiple config files in vNext

### ISSUE THREAD

**Issue by sterit** [Azure/vdc#114]
Mapping should be available for multiple config files in vNext. There are scenarios where a company (especially conglomerates) that are comprised of multiple business units. They may have business units that operate mostly independent, but still have a corporate IT. So, they would want to use the same orchestration code (shared modules, etc.) but have just different environments. Having multiple config files would then allow them to accomplish this, and have different audit storage for each main"environment"

**Comment by senthilkungumaraj** [comment]
Enhancements implemented and merged to the next branch as part of the PR below:

https://github.com/Azure/vdc/pull/134
