### ISSUE TITLE
Customizing Validation Resource Group in vNext

### ISSUE THREAD

**Issue by sterit** [Azure/vdc#117]
The validation resource group should have customization exposed through some type of common file (toolkit.config as an example). It should allow for customizing the naming, as well as putting tags on the resource group.

- **Tags**: This is important as templates can call the resourceGroup() ARM function and get configuration info from the RG. If you are getting information from a tag to use in your template, validation will fail entirely as the template will be flagged as invalid as there are no tags on the resource group. Tags can be used in the template for various automation reasons, or even just to inherit the tags down directly to the resource. 
- **Naming**: This is important as many customers may have policies around naming convention based on a regex. If the name for the validation RG is out of policy, it could trigger an audit alert, or if the policy is a deny policy, it could even block the RG from being created, which would break validation importantly.

**Comment by senthilkungumaraj** [comment]
Enhancements implemented and merged to the next branch as part of the PR below:

https://github.com/Azure/vdc/pull/134
