### ISSUE TITLE
Need to be able to grant RBAC roles to AKS infrastructure resource group

### ISSUE THREAD

**Issue by dave-read** [Azure/vdc#14]
AKS infrastructure (e.g. VMs, load balancers, etc) are created in a resource group that's created as part of creating the cluster.  We need to be able to assign RBAC roles to that resource group so that operations staff can interact with those resources.   The name of that resource group is not known until after the cluster is created, so the role assignment process needed to happen after the cluster creation and the cluster creation needs to include the resource group name and ID as output parameters.

**Comment by jorgecotillo** [comment]
Closing the issue since the code got merged.
