### ISSUE TITLE
Policy API Version

### ISSUE THREAD

**Issue by jceval** [Azure/vdc#16]
During policy assignment at the resource group level, the vdc engine is deploying the defined policies assignment using API version '2018-03-01'. This is causing an error on any policy using effect type 'deployIfNotExists', as it is not supported in this API Version.

Update Microsoft.Authorization/policyAssignments and Microsoft.Authorization/policyDefinintion API version to minimum '2018-05-01' to support added effect types.

**Comment by jorgecotillo** [comment]
We are working on reproducing the issue.

Can you please make sure to delete your docker image and create it again? Deleting the image and creating it again will download the latest azure sdk packages.

**Comment by jorgecotillo** [comment]
After reproducing the error, this issue turned out to be a feature update. The code has been updated to use Azure Policy SDK api-version 2018-05-01.

**Comment by jorgecotillo** [comment]
Code has been merged
 @jceval please confirm that the issue has been resolved.

**Comment by jorgecotillo** [comment]
@jceval closing the issue, please re-open if the issue persists.
