### ISSUE TITLE
AKS workload needs Azure firewall outbound "allow" network rule on port 22

### ISSUE THREAD

**Issue by dave-read** [Azure/vdc#20]
An AKS cluster currently creates an outbound tunnel on port 22 to the API server to allow connections from the control plane back to agent pool nodes (VMs).  Without this port open, the cluster will start, but operations like kubectl logs and kubectl exec will fail since the tunnel does not exits.   

If you check the Azure firewall logs in the Log analytics workspace, you can see the deny messages for outbound connection attempts from the Pod tunnelfront on port 22 to create the tunnel.

**Comment by senthilkungumaraj** [comment]
Addressed in https://github.com/Azure/vdc/pull/22
