### ISSUE TITLE
AKS workload needs Azure load balancer probe(s) enabled in NSG

### ISSUE THREAD

**Issue by dave-read** [Azure/vdc#21]
The current AKS archetype creates NSG rules to limit traffic to (within the VNET) ssh, http, and https.  However these rules look like they are blocking the health probe port that's assigned when a Kubernetes Service of type LoadBalancer is created.  

"name": "allow-ssh",
"name": "allow-http",
"name": "allow-https",
"name": "deny-internet",
"name": "deny-vnet",

Adding an allow rule with source Service Tag LoadBalancer appears to resolve this.

**Comment by senthilkungumaraj** [comment]
Addressed in https://github.com/Azure/vdc/pull/22
