### ISSUE TITLE
Rename the Log Analytics Resource Group to generalize for diagnostics

### ISSUE THREAD

**Issue by albertwo1978** [Azure/vdc#25]
Several workloads (ex. AKS) deploy multiple monitoring/logging resources as part of the archetype deployment. These resources are deployed to the same RG as Log Analytics currently labeled:

{org}-{deployment-name}-la-rg

Can we change this to something more general. Example:

{org}-{deployment-name}-diag-rg

The current naming convention is a little deceiving.

**Comment by jorgecotillo** [comment]
Closing since this has been addressed.
