### ISSUE TITLE
Why no mention of Azure Virtual WAN?

### ISSUE THREAD

**Issue by aarsan** [Azure/vdc#6]
I'm curious why there is no mention of Azure Virtual WAN. My understanding is that Azure Virtual WAN is pivotal in the hub/spoke design, going forward. Is this not the case?

Thanks,
Ahmet

**Comment by telmosampaio** [comment]
Hi Ahmet, we work with proven practices. Artifacts that have actually been deployed to production in a customer environment. With that in mind, keep an eye out, since a vWAN reference architecture is in our backlog.
