### ISSUE TITLE
Key Vault validation

### ISSUE THREAD

**Issue by jceval** [Azure/vdc#9]
Error when validating key vault deployment.

The error only shows when running ‘python vdc.py validate’ and not if we actually use the create argument.

From trying to track down what ‘environment_keys’ is, it looks to be related to the argument values passed by the Bash Cmd. 

ERROR: 
**orchestration.resource_validation - ERROR - __init__() missing 1 required positional argument: 'environment_keys'**

**Comment by jorgecotillo** [comment]
@jceval PR got merged, can you please get the latest?

**Comment by bennage** [comment]
Please reopen this if the issues reoccurs. Thanks.
