### ISSUE TITLE
ConvertTo-Json with AsHashtable option does not maintain order of the properties

### ISSUE THREAD

**Issue by senthilkungumaraj** [Azure/vdc#95]
ConvertTo-Json with AsHashtable option does not maintain order of the properties. This leads to invalid positional parameters being passed to the shell script that relies on positional parameters.

**Comment by jorgecotillo** [comment]
Please update the title, the issue is when you run ConvertFrom-Json with AsHashtable flag.

**Comment by senthilkungumaraj** [comment]
Resolved as part of the PR  - https://github.com/Azure/vdc/pull/122
